# Generated by Django 3.2.6 on 2021-08-30 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='telefone',
            new_name='nm_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='email',
            new_name='unidade_medida',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='sobrenome',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='mostrar',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='id_produto',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_fornecedor',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(default='premium', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produto',
            name='vl_unidade',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
